name: aws_services
description: "Dart package designed to simplify integrations with AWS services."
version: 1.0.0
homepage: https://github.com/inkopon/aws_services

environment:
  sdk: ^3.5.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  crypto: ^3.0.6
  http_client: ^1.5.3
  xml: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0